### ISSUE TITLE
Strategy is not executed if I change start time to 9:16

### ISSUE THREAD

**Issue by itskilari** [sreenivasdoosa/sdoosa-algo-trade-python#14]
@sreenivasdoosa 
Hi Srini,
I want to execute straddle strategy at 9:16, so I changed _self.startTimestamp = Utils.getTimeOfToDay(9, 16, 0)_ BUT strategy is not executed. 
From below logs i see wait time is applying to strategy as well...
2021-05-26 09:06:37: Algo started.
2021-05-26 09:06:37: ShortStraddleNF: Waiting for 503 seconds till market opens...
2021-05-26 09:15:00: ShortStraddleNF: Waiting for 563 seconds till startegy start timestamp reaches..._

**Comment by sreenivasdoosa** [comment]
Pl send me your complete strategy file.

**Comment by itskilari** [comment]
Hi Srini, Thanks for response.
Strategy is same as your 'ShortStraddleBNF.py ' but I have applied it on Nifty and changed strategy start time to 9:16 self.startTimestamp = Utils.getTimeOfToDay(9, 16, 0).
below is the strategy code:

**Comment by itskilari** [comment]
import logging
from datetime import datetime

from instruments.Instruments import Instruments
from models.Direction import Direction
from models.ProductType import ProductType
from strategies.BaseStrategy import BaseStrategy
from utils.Utils import Utils
from trademgmt.Trade import Trade
from trademgmt.TradeManager import TradeManager


class ShortStraddleNF(BaseStrategy):
    __instance = None

    @staticmethod
    def getInstance():  # singleton class
        if ShortStraddleNF.__instance == None:
            ShortStraddleNF()
        return ShortStraddleNF.__instance

    def __init__(self):
        if ShortStraddleNF.__instance != None:
            raise Exception("This class is a singleton!")
        else:
            ShortStraddleNF.__instance = self
        # Call Base class constructor
        super().__init__("ShortStraddleNF")
        # Initialize all the properties specific to this strategy
        self.productType = ProductType.MIS
        self.symbols = []
        self.slPercentage = 80
        self.targetPercentage = 0
        self.startTimestamp = Utils.getTimeOfToDay(9, 16, 0)  # When to start the strategy. Default is Market start time
        self.stopTimestamp = Utils.getTimeOfToDay(14, 0,
                                                  0)  # This is not square off timestamp. This is the timestamp after which no new trades will be placed under this strategy but existing trades continue to be active.
        self.squareOffTimestamp = Utils.getTimeOfToDay(14, 30, 0)  # Square off time
        self.capital = 600000  # Capital to trade (This is the margin you allocate from your broker account for this strategy)
        self.leverage = 0
        self.maxTradesPerDay = 2  # (1 CE + 1 PE) Max number of trades per day under this strategy
        self.isFnO = True  # Does this strategy trade in FnO or not
        self.capitalPerSet = 100000  # Applicable if isFnO is True (1 set means 1CE/1PE or 2CE/2PE etc based on your strategy logic)

    def canTradeToday(self):
        # Even if you remove this function canTradeToday() completely its same as allowing trade every day
        return True

    def process(self):
        now = datetime.now()
        if now < self.startTimestamp:
            return
        if len(self.trades) >= self.maxTradesPerDay:
            return

        # Get current market price of Nifty Future
        futureSymbol = Utils.prepareMonthlyExpiryFuturesSymbol('NIFTY')
        quote = self.getQuote(futureSymbol)
        if quote == None:
            logging.error('%s: Could not get quote for %s', self.getName(), futureSymbol)
            return

        ATMStrike = Utils.getNearestStrikePrice(quote.lastTradedPrice, 50)
        logging.info('%s: Nifty CMP = %f, ATMStrike = %d', self.getName(), quote.lastTradedPrice, ATMStrike)

        ATMCESymbol = Utils.prepareWeeklyOptionsSymbol("NIFTY", ATMStrike, 'CE')
        ATMPESymbol = Utils.prepareWeeklyOptionsSymbol("NIFTY", ATMStrike, 'PE')
        logging.info('%s: ATMCESymbol = %s, ATMPESymbol = %s', self.getName(), ATMCESymbol, ATMPESymbol)
        # create trades
        self.generateTrades(ATMCESymbol, ATMPESymbol)

    def generateTrades(self, ATMCESymbol, ATMPESymbol):
        numLots = self.calculateLotsPerTrade()
        quoteATMCESymbol = self.getQuote(ATMCESymbol)
        quoteATMPESymbol = self.getQuote(ATMPESymbol)
        if quoteATMCESymbol == None or quoteATMPESymbol == None:
            logging.error('%s: Could not get quotes for option symbols', self.getName())
            return

        self.generateTrade(ATMCESymbol, numLots, quoteATMCESymbol.lastTradedPrice)
        self.generateTrade(ATMPESymbol, numLots, quoteATMPESymbol.lastTradedPrice)
        logging.info('%s: Trades generated.', self.getName())

    def generateTrade(self, optionSymbol, numLots, lastTradedPrice):
        trade = Trade(optionSymbol)
        trade.strategy = self.getName()
        trade.isOptions = True
        trade.direction = Direction.SHORT  # Always short here as option selling only
        trade.productType = self.productType
        trade.placeMarketOrder = True
        trade.requestedEntry = lastTradedPrice
        trade.timestamp = Utils.getEpoch(self.startTimestamp)  # setting this to strategy timestamp

        isd = Instruments.getInstrumentDataBySymbol(optionSymbol)  # Get instrument data to know qty per lot
        trade.qty = isd['lot_size'] * numLots

        trade.stopLoss = Utils.roundToNSEPrice(trade.requestedEntry + trade.requestedEntry * self.slPercentage / 100)
        trade.target = 0  # setting to 0 as no target is applicable for this trade

        trade.intradaySquareOffTimestamp = Utils.getEpoch(self.squareOffTimestamp)
        # Hand over the trade to TradeManager
        TradeManager.addNewTrade(trade)

    def shouldPlaceTrade(self, trade, tick):
        # First call base class implementation and if it returns True then only proceed
        if super().shouldPlaceTrade(trade, tick) == False:
            return False
        # We dont have any condition to be checked here for this strategy just return True
        return True

    def getTrailingSL(self, trade):
        if trade == None:
            return 0
        if trade.entry == 0:
            return 0
        lastTradedPrice = TradeManager.getLastTradedPrice(trade.tradingSymbol)
        if lastTradedPrice == 0:
            return 0

        trailSL = 0
        profitPoints = int(trade.entry - lastTradedPrice)
        if profitPoints >= 10:
            factor = int(profitPoints / 10)
            trailSL = Utils.roundToNSEPrice(trade.initialStopLoss - factor * 10)
        logging.info('%s: %s Returning trail SL %f', self.getName(), trade.tradingSymbol, trailSL)
        return trailSL

**Comment by sreenivasdoosa** [comment]
I hope you started Algo, then from browser clicked on Login to Broker and
completed login flow and clicked on start Algo button

thereafter see logs....

Code looks good, now send me the completed log file.

**Comment by itskilari** [comment]
Yes i followed mention process.
Appl. working fine if i start Algo after market open...and strategy executing at 9:16. 
If i start Algo before market open time (before 9:15) 
for example 9:09(Today) and wait time is 304 seconds.. after market open strategy wait time must be 60 secs right as my strategy start time is at 9:16 but 60 seconds adding to market start wait time(364 secs) and strategy is executing at 9:23..

**_2021-05-28 09:09:56: ShortStraddleNF: Waiting for 304 seconds till market opens...
2021-05-28 09:15:01: ShortStraddleNF: Waiting for 364 seconds till startegy start timestamp reaches..._**

Please find log here : https://docs.google.com/document/d/1g32BqshkBHQORfpF4PuhXv1uqruBTPZFEJuBMcwKoH0/edit?usp=sharing 

Thanks

**Comment by sreenivasdoosa** [comment]
Thanks for pointing it out. There is a small bug. I fixed it now. Here is
the commit
https://github.com/sreenivasdoosa/sdoosa-algo-trade-python/commit/9f5a367f668d3a35e3937807a52d1cc49464de7b

Pl pull/download the latest code and now it should place orders at 09:16 AM.

Thanks,
Sreenivas

**Comment by itskilari** [comment]
Thank you 🙏
