### ISSUE TITLE
Enhancement: usage of spot price of index instead of future price of index

### ISSUE THREAD

**Issue by vasanthkumarv** [sreenivasdoosa/sdoosa-algo-trade-python#19]
Usage of LTP of spot price instead of future price to select the near ATM strike. Most of retail uses stockmock to do backtest which is based on spot price.

**Comment by rrajesh145** [comment]
> Usage of LTP of spot price instead of future price to select the near ATM strike. Most of retail uses stockmock to do backtest which is based on spot price.

You can check here for your requirement. I have updated that and pushed it 
https://github.com/rrajesh145/algo_tradiing/commit/9392d97324c6a043256d9c223951a1ea97da6be2

**Comment by vasanthkumarv** [comment]
Thanks @rrajesh145 I too added similar function to Quotes.py

`  @staticmethod
  def getSpotLTP(tradingSymbol):
    broker = Controller.getBrokerName()
    brokerHandle = Controller.getBrokerLogin().getBrokerHandle()
    quote = None
    if broker == "zerodha":
        bQuoteResp = brokerHandle.quote(tradingSymbol)
        bQuote = bQuoteResp[tradingSymbol]
        quote = Quote(tradingSymbol)
        quote.lastTradedPrice = bQuote['last_price']    
        
    return quote`

**Comment by vasanthkumarv** [comment]
update to strategy file
--------------------------   
 # Get current market price of Nifty Future
    #futureSymbol = Utils.prepareMonthlyExpiryFuturesSymbol('BANKNIFTY')
    spotSymbol = "NSE:NIFTY BANK"
    quote = self.getSpotLTP(spotSymbol)
    if quote == None:
      logging.error('%s: Could not get LTP for %s', self.getName(), spotSymbol)
      return

**Comment by vasanthkumarv** [comment]
closing
