### ISSUE TITLE
Youtube Playlist is not available

### ISSUE THREAD

**Issue by mohitag86** [sreenivasdoosa/sdoosa-algo-trade-python#42]
Hello Sir,

The YouTube playlist is not available. Request you to upload it again.

https://www.youtube.com/playlist?list=PL-yBsBIJqqBn6oMMgLjvhCTNT-zLXYmoW

**Comment by alwin48** [comment]
Yes the link is not valid.

**Comment by sreenivasdoosa** [comment]
Youtube playlist and videos are public now.
