### ISSUE TITLE
NameError: name 'getTimeOfDay' is not defined

### ISSUE THREAD

**Issue by itskilari** [sreenivasdoosa/sdoosa-algo-trade-python#6]
Hi Getting Name error Can you please check?

File ".....\src\utils\Utils.py", line 80, in getTimeOfToDay
    return getTimeOfDay(hours, minutes, seconds, datetime.now())
**NameError: name 'getTimeOfDay' is not defined**

I am using Pycharm. though 'getTimeOfDay' is already defined, throwing above error..
Thanks,

**Comment by itskilari** [comment]
This is resolved by adding Utils.getTimeOfDay().. Thanks

**Comment by ENGINEERDK** [comment]
Thanks, I also fixed mine.
